# Page settings
baseurl = "https://www.ticnsp.org/"
BaseURL = "https://www.ticnsp.org/"
title = "tic.nsp"
languageCode = "en-us"
theme = "hugo-elate-theme"

[params]
  
  custom_css = ["css/override.css"]

  # Meta
  author = "Ricardo Roman"
  description = "TIC NSP Website"
  email = "ricardo.roman+web@ticnsp.org"

  # Google Maps Javascript API Key (if not set will default to not passing a key)
  googleMapsApiKey = ""

  # Facebook / Twitter
  [params.sidebar]
    avatar = "bg1.jpg"

  # Navigation
  [params.navigation]
    brand = "tic.nsp"
    home = "Inicio"
    # work = "Work"
    # testimonials = "Testimonials"
    services = "Servicios"
    about = "Nosotros"
    contact = "Contacto"

    # You can add custom links before or after the default links
    # Assign a weight to define the order
    
    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    #[[menu.postpend]]
    #  url = "http://gohugo.io"
    #  name = "External link"
    #  weight = 10
  
  # Hero section
  [params.hero]
    title = "Enséñale al niño el camino que ha de seguir"
    subtitle = 'Talleres Infantiles Católicos'
 
  # Intro section
  # Available icons: http://simplelineicons.com/
  [params.intro]

  [[params.intro.item]]
    title = "Talleres"
    description = "En nuestros talleres, los niños conocen a Dios y a la vez se divierten aprendiendo cosas nuevas, desde deportes, bailes, actividades creativas y más."
    url = "#fh5co-services"
    button = "Ver más"
    icon = "icon-bulb"
    img = "img_7.jpg"

  [[params.intro.item]]
    title = "Infantiles"
    description = "Queremos que los niños estén cerca de Dios en su infancia. Para niños de 6 a 11 años de edad, puede ser antes o después de cursar el catecismo."
    url = "#fh5co-contact"
    button = "Contáctanos"
    icon = "icon-child"
    img = "img_8.jpg"

  [[params.intro.item]]
    title = "Católicos"
    description = "Dios es el centro de TIC y los niños lo viven en las alabanzas, talleres, receso y por supuesto, catequesis. Dios forma parte del 100% de nuestras actividades."
    url = "#fh5co-services"
    button = "Ver más"
    icon = "icon-plus"
    img = "img_10.jpg"

  [params.intro.video]
    enable = false
    title = "Watch the video"
    icon = "icon-play2"
    url = "https://vimeo.com/channels/staffpicks/93951774"


  # Work section
  [params.work]
    enable = false
    title = "Work"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."
    footertext = '** Demo images from <a href="http://plmd.me/" target="_blank">plmd.me</a>'

    [[params.work.row]]
      img = "work_1.jpg"
      alt = "Image2"
      title = "Project 1"
      subtitle = "Branding"

    [[params.work.row]]
      img = "work_2.jpg"
      alt = "Image2"
      title = "Project 2"
      subtitle = "Design"

    [[params.work.row]]
      img = "work_3.jpg"
      alt = "Image3"
      title = "Project 3"
      subtitle = "Design"

    [[params.work.row]]
      img = "work_4.jpg"
      alt = "Image4"
      title = "Project 4"
      subtitle = "Design"

    [[params.work.row]]
      img = "work_5.jpg"
      alt = "Image5"
      title = "Project 5"
      subtitle = "Design"

    [[params.work.row]]
      img = "work_6.jpg"
      alt = "Image6"
      title = "Project 6"
      subtitle = "Design"

  # Testimonials section
  [params.testimonials]
    enable = false
    title = "Testimonials"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."

    [[params.testimonials.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.&rdquo;"
      person = 'Jean Doe, CEO <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person1.jpg"
      alt = "Person1"

    [[params.testimonials.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean. Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.&rdquo;"
      person = 'John Doe, Senior UI <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person2.jpg"
      alt = "Person2"

    [[params.testimonials.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. &rdquo;"
      person = 'Chris Nash, Director <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person3.jpg"
      alt = "Person3"
    



  # Services section
  [params.services]
    enable = true
    title = "Servicios"
    description = "TIC se dedica a anunciar el Evangelio a los niños; por eso, en un curso tienes muchas oportunidades de conocer a Dios en formas únicas."

    [[params.services.item]]
      title = "Catequesis"
      description = "Lo más importante del curso. En las catequesis, los niños aprenden más de Dios, de su Fe y de la Iglesia en actividades divertidas y especiales para su edad."
      icon = "icon-book2"

    [[params.services.item]]
      title = "Talleres"
      description = "En los talleres, los niños aprenden habilidades nuevas en categorías como deportes, cocina, baile o ciencias. Los talleres construyen sus actividades encima de los temas de catequesis."
      icon = "icon-flag"
    [[params.services.item]]
      title = "Retiro"
      description = "En un retiro semestral, los niños viven un encuentro a solas con Dios, como Jesús mismo nos invita en Mc 6:31, a descansar en un lugar solitario con él."
      icon = "icon-heart2"

      [[params.services.item]]
      title = "Día de juego"
      description = "Un día al semestre todos somos como niños y nos dedicamos a divertirnos. En todos los juegos, como en todo nuestro curso, Jesús está presente."
      icon = "icon-sun"

  # About section
  [params.about]
    enable = true
    title = "El equipo"
    description = "Nuestro equipo está formado por jóvenes entusiasmados por servir a Dios y compartir su Evangelio, especialmente con los niños. Conoce a nuestros coordinadores generales:"

    [[params.about.item]]
      name = "Andrea Ortiz"
      position = "Coordinación General"
      description = "UTEP Miner - BA Graphic Design"
      img = "cg1.jpg"
      alt = "Coordinador General"
      social = [
        ["icon-facebook", "https://facebook.com/tic.nsp"],
        ["icon-twitter", "https://twitter.com/ticnsp"],
        ["icon-instagram", "https://www.instagram.com/tic.nsp"]
      ]

    [[params.about.item]]
      name = "Ricardo Román"
      position = "Coordinación General"
      description = "ExaTEC - MATI | CMU Alumni - MSIT"
      img = "cg2.jpg"
      alt = "Coordinador General"
      social = [
        ["icon-facebook", "https://facebook.com/tic.nsp"],
        ["icon-twitter", "https://twitter.com/ticnsp"],
        ["icon-instagram", "https://www.instagram.com/tic.nsp"]
      ]

  # Counters section
  [params.counters]
    enable = true
    title = "Estadísticas Semestrales"
    background = "bg2.jpg"

    [[params.counters.item]]
      description = "Semestres de experiencia"
      icon = "icon-briefcase"
      from = 0
      to = 18
      interval = 50
      speed = 2000

    [[params.counters.item]]
      description = "Coordinadores"
      icon = "icon-people"
      from = 0
      to = 34
      interval = 50
      speed = 2000

    [[params.counters.item]]
      description = "Niños inscritos"
      icon = "icon-check"
      from = 0
      to = 45
      interval = 50
      speed = 2000

    [[params.counters.item]]
      description = "Talleres impartidos"
      icon = "icon-flag"
      from = 0
      to = 5
      interval = 50
      speed = 2000

  # Contact section
  [params.contact]
    enable = true
    map = true
    form = false
    title = "Contacto"
    description = "¿Necesitas información? Contáctanos"
    
    # Available icons: http://simplelineicons.com/
    details = [
        ["icon-home", "Calle Rancho el Retiro Sur 3517, Pradera Dorada, 32618 <br> Ciudad Juárez, Chihuahua, México"],
        ["icon-phone", "+1 (915) 228-4282‬ (escucharás nuestro más reciente aviso)"],
        ["icon-envelope", "padres@ticnsp.org"],
        ["icon-globe", '<a href="http://ticnsp.org/" target="_blank">TICNSP.org</a>']
      ]

    name = "Name"
    email = "Email"
    phone = "Phone"
    message = "Message"
    button = "Send message"

  # Footer section
  [params.footer]
    enable = true
    copyright = '2019 &copy; Talleres Infantiles Católicos. El plagio es pecado. <br>Desarrollado con <i class="icon-heart2"></i> por <a href="http://www.ticnsp.org/" target="_blank">TICNSP.org</a>'
    links = [
        ["icon-facebook", "https://facebook.com/tic.nsp"],
        ["icon-twitter", "https://twitter.com/ticnsp"],
        ["icon-instagram", "https://www.instagram.com/tic.nsp"]
      ]
